import { Color } from "three";

const AMBIENT_LIGHT_COLOR = "#F8F9FA";
const BACKGROUND_COLOR = "#212529";
const CHARTED_COLOR = "#FFFFFF";
const CURSOR_COLOR = "#FFFFFF";
const DIRECITONAL_LIGHT_COLOR = "#F8F9FA";
const ISLAND_COLOR = "#ADB5BD";
const WATER_COLOR = "#212529";

export {
  AMBIENT_LIGHT_COLOR,
  BACKGROUND_COLOR,
  CHARTED_COLOR,
  CURSOR_COLOR,
  DIRECITONAL_LIGHT_COLOR,
  ISLAND_COLOR,
  WATER_COLOR,
};
