AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation for a static website using S3 and Cloudfront

Parameters:  
  CloudFrontHostedZoneId:
    Description: 'This is the Cloudfront Hosted Zone Id. See the bottom of this page http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid'
    Type: String
    Default: Z2FDTNDATAQYW2
  Environment:
    Description: The environment being deployed to
    Type: String
    AllowedValues:
      - dev
      - prod
  NakedDomain:
    Description: The Naked Domain for the static website
    Type: String

Conditions: 
  CreateProdResources: !Equals [ !Ref Environment, prod ]

Mappings: 
  EnvironmentSubdomain: 
    dev: 
      Subdomain: dev
    prod: 
      Subdomain: www

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ ".", [ !FindInMap [ EnvironmentSubdomain, !Ref Environment, Subdomain ], !Ref NakedDomain ] ]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket: !Join [ ".", [ !FindInMap [ EnvironmentSubdomain, !Ref Environment, Subdomain ], !Ref NakedDomain ] ]
      PolicyDocument: {
        "Version":"2012-10-17",
        "Statement": [
          {
            "Sid":"AddPerm",
            "Effect":"Allow",
            "Principal": "*",
            "Action": [ "s3:GetObject" ],
            "Resource": [ !Join [ "", [ "arn:aws:s3:::", !FindInMap [ EnvironmentSubdomain, !Ref Environment, Subdomain ], ".", !Ref NakedDomain, "/*" ] ] ]
          }
        ]
      }
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Join [ ".", [ !FindInMap [ EnvironmentSubdomain, !Ref Environment, Subdomain ], !Ref NakedDomain ] ]
        Enabled: True
        Origins:
          - DomainName: !Select
              - 1
              - !Split ["//", !GetAtt Bucket.WebsiteURL]
            Id: origin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: origin
          DefaultTTL: 5
          MaxTTL: 30
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          SslSupportMethod: sni-only
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Join [ "", [ !Ref NakedDomain , "." ] ] 
      RecordSets:
        - Name: !Join [ ".", [ !FindInMap [ EnvironmentSubdomain, !Ref Environment, Subdomain ], !Ref NakedDomain ] ]
          Type: A
          AliasTarget:
            HostedZoneId: !Ref CloudFrontHostedZoneId
            DNSName: !GetAtt CloudFrontDistribution.DomainName
        - Name: !Join [ ".", [ !FindInMap [ EnvironmentSubdomain, !Ref Environment, Subdomain ], !Ref NakedDomain ] ]
          Type: AAAA
          AliasTarget:
            HostedZoneId: !Ref CloudFrontHostedZoneId
            DNSName: !GetAtt CloudFrontDistribution.DomainName
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join [ ".", [ !FindInMap [ EnvironmentSubdomain, !Ref Environment, Subdomain ], !Ref NakedDomain ] ]
      DomainValidationOptions:
        - DomainName: !Join [ ".", [ !FindInMap [ EnvironmentSubdomain, !Ref Environment, Subdomain ], !Ref NakedDomain ] ]
          ValidationDomain: !Ref NakedDomain

  NakedBucket:
    Type: AWS::S3::Bucket
    Condition: CreateProdResources
    Properties:
      BucketName: !Ref NakedDomain
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Join [ ".", [ !FindInMap [ EnvironmentSubdomain, !Ref Environment, Subdomain ], !Ref NakedDomain ] ]
          Protocol: https
  NakedCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Condition: CreateProdResources
    Properties:
      DistributionConfig:
        Aliases: 
          - !Ref NakedDomain
        Enabled: True
        Origins:
          - DomainName: !Select
              - 1
              - !Split ["//", !GetAtt NakedBucket.WebsiteURL]
            Id: origin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: origin
          DefaultTTL: 5
          MaxTTL: 30
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref NakedSSLCertificate
          SslSupportMethod: sni-only
  NakedSSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: CreateProdResources
    Properties:
      DomainName: !Ref NakedDomain
  NakedDNS:
    Type: AWS::Route53::RecordSetGroup
    Condition: CreateProdResources
    Properties:
      HostedZoneName: !Join [ "", [ !Ref NakedDomain , "." ] ] 
      RecordSets:
        - Name: !Ref NakedDomain
          Type: A
          AliasTarget:
            HostedZoneId: !Ref CloudFrontHostedZoneId
            DNSName: !GetAtt NakedCloudFrontDistribution.DomainName
        - Name: !Ref NakedDomain
          Type: AAAA
          AliasTarget:
            HostedZoneId: !Ref CloudFrontHostedZoneId
            DNSName: !GetAtt NakedCloudFrontDistribution.DomainName
